FROM rust:1.76-slim-bookworm

RUN dpkg --add-architecture i386 \
    && apt-get update && apt-get install -y --no-install-recommends \
        curl wget unzip git gcc g++ make file bzip2 \
    && rm -rf /var/lib/apt/lists/*

RUN wget -q https://dl.google.com/android/repository/android-ndk-r26c-linux.zip \
    && unzip -q android-ndk-r26c-linux.zip -d /opt/ \
    && rm android-ndk-r26c-linux.zip

ENV ANDROID_NDK_HOME=/opt/android-ndk-r26c
ENV PATH=${PATH}:${ANDROID_NDK_HOME}

RUN cargo install cargo-ndk
RUN rustup target add aarch64-linux-android armv7-linux-androideabi

WORKDIR /build
